#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: training
#spec:
#  selector:
#    matchLabels:
#      app: training
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: training
#    spec:
#      containers:
#        - name: training
#          image: training:1.0
#          ports:
#            - containerPort: 8080
#          env:   # Setting Environmental Variables
#            - name: DB_HOST   # Setting Database host address
#              value: mysql
#            - name: DB_NAME  # Setting Database name
#              value: training
#            - name: DB_USERNAME  # Setting Database username
#              value: root
#            - name: DB_PASSWORD # Setting Database password
#              value: root
## This seperator --- below is MANDATORY!!!
#---
#
## Define a 'Service' To Expose the application
#apiVersion: v1
#kind: Service
#metadata:
#  name: training
#spec:
#  ports:
#    - protocol: "TCP"
#      port: 8080    # Port inside the cluster
#      targetPort:   # Port exposed to the outside
#  selector:
#    app: root-v2
#  type: NodePort